from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider

import json

from langchain.llms import openai
from langchain.embeddings import OpenAIEmbeddings
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain.vectorstores.cassandra import Cassandra
from datasets import load_dataset

from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv('OPEN_AI_API_KEY')

# This secure connect bundle is autogenerated when you download your SCB, 
# if yours is different update the file name below
myCasandraVStore = None
def connect_to_db():
    cloud_config= {
    'secure_connect_bundle': 'secure-connect-prep-mate-db.zip'
    }

    # This token JSON file is autogenerated when you download your token, 
    # if yours is different update the file name below
    with open("tsgsekgothe6969@gmail.com-token.json") as f:
        secrets = json.load(f)

    CLIENT_ID = secrets["clientId"]
    CLIENT_SECRET = secrets["secret"]

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    session = cluster.connect()
    return session

def create_table(table_name):
    embeddings = OpenAIEmbeddings(open_ai_key=api_key)
    myCasandraVStore=Cassandra(
        embeddings=embeddings,
        session=connect_to_db(),
        key_space="prep_mate",
        table_name=table_name
    )

    return myCasandraVStore

def add_data_to_vector_table(data_table, data):
    data = data.split("\n")
    data_table.add_texts(data)

def get_vector_index_wrapper():
    if myCasandraVStore is None:
        return None
    return VectorStoreIndexWrapper(myCasandraVStore)